# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturereading',
            name='unit',
            field=models.CharField(choices=[('f', 'Fahrenheit'), ('c', 'Celsius')], default='f', max_length=1),
        ),
    ]
